# Dependabot configuration:
# - only security updates, thus number of PRs limited to 0
#
version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    # Disable version updates for dependencies
    open-pull-requests-limit: 0
