[package]
name = "ns-dbg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive", "env"] }
env_logger = "0.11.5"
exitcode = "1.1.2"
log = "0.4.22"
procfs = { version= "0.17.0" }
rustix = { version = "0.38.37", features = ["process", "thread", "mount", "fs"] }
